services:

  backend:
    build:
      context: "./backend"
    environment:
      - PORT=8080
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - db

  # frontend:
  #   build:
  #     context: "./frontend"
  #   ports:
  #     - 3000:3000

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example

